services:
  auth-app:
    container_name: auth-app
    environment:
      TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8081:8081"
