# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go tests

on:
  [push]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: test-env
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install golint and go vet
        run: |
          go install github.com/rauzh/go-complexity-analysis/cmd/complexity@9a7cad4
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2

      - name: Launch govet
        if: always()
        run: |
          cd backend
          go vet -vettool="$(which complexity)" --cycloover 10 --halsteadover 40 ./...
#          if [ $? -ne 0 ]; then exit 1; fi

      - name: Launch golint
        if: always()
        run: |
          cd backend
          golangci-lint run ./...
#          if [ $? -ne 0 ]; then exit 1; fi

  tests:
#    needs: lint
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'
          cache-dependency-path: backend/go.sum

      - name: Install dependencies
        run: cd backend && go mod tidy

      - name: Run unit tests
        id: unit
        run: cd backend && make ci-unit -i

      - name: Run integration tests
        id: integration
        if: steps.unit.outcome == 'success'
        run: cd backend && make ci-integration -i

      - name: Run end to end tests
        id: e2e
        if: steps.integration.outcome == 'success'
        run: cd backend && make ci-e2e

      - name: LS
        if: always()
        run: ls ${GITHUB_WORKSPACE}

      - name: Add environment properties and concat allure results
        run: cd backend && make ci-concat-reports

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
      
